spring:
  datasource:
    url: jdbc:h2:file:./data/testdb
    username: "sa"
    password: "pass"
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop # Hibernate ddl auto (create, create-drop, validate, update, none)
