runtime: java11
instance_class: F2

# Explicitly set the memory limit and maximum heap size for the Spring Boot app
env_variables:
  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=1024m -XX:ActiveProcessorCount=2 -Xmx128m"
  
  

# runtime: java11
# instance_class: B2

# Explicitly set the memory limit and maximum heap size for the Spring Boot app
# env_variables:
#  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=1024m -XX:ActiveProcessorCount=2 -Xmx128m"
  
# basic_scaling:
#  max_instances: 2
#  idle_timeout: 30m
