# Generated by Django 3.2.8 on 2021-12-16 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_nro_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('nro_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_registro', models.DateTimeField()),
                ('moneda', models.CharField(max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
            ],
        ),
    ]
