server:
  port: '8085'
spring:
  profiles:
    active: prod
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: ${USER}
    url: jdbc:postgresql://localhost:5432/restfulapi
    password: ${PASS}
  jpa:
    generate-ddl: 'true'
    database: POSTGRESQL
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    username: ${USER}
    url: jdbc:postgresql://localhost:5432/restfulapi_qa
    password: ${PASS}
  jpa:
    generate-ddl: 'true'
    database: POSTGRESQL
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: ${USER}
    url: jdbc:postgresql://localhost:5432/restfulapi_prod
    password: ${PASS}
  jpa:
    generate-ddl: 'true'
    database: POSTGRESQL
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: postgres