security.jwt.token.secret-key: my-secret-key
spring:
  datasource:
    username: ${USER}
    url: jdbc:postgresql://localhost:5432/back_db
    platform: postgres
    password: ${PASS}
  jpa:
    generate-ddl: 'true'
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    show-sql: 'true'
    # Crear un esquema al inicio de la app
    hibernate:
      ddl-auto: create-drop
server:
  port: 8081