# Generated by Django 3.2.8 on 2021-12-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('direccion', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
