spring:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/concesionario
    username: ${USER}
    password: ${PASS}
server:
  port: 9090
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    path: /swagger-ui.html

